### ISSUE TITLE
Issue with importing _formants

### ISSUE THREAD

**Issue by YolandaZheng** [mwv/praat_formants_python#1]
Hello, I'm having some trouble with importing your library. When I try to run the statement `import praat_formants_python as pfp`, I get the error 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Yolanda/Downloads/praat_formants_python-master/praat_formants_python/__init__.py", line 7, in <module>
    from _formants import file2formants, clear_formant_cache, formants_at_time, \
ImportError: No module named '_formants'
```

I'm running python 3.4.3 on OS X 10.11.4
Do you have any suggestions as to how to fix this?

Thanks so much 👼

**Comment by mwv** [comment]
This code was written for python 2, but it should probably work on python 3 as well. I'll have a look. In the meantime, did you install through setup.py as described in the readme?

**Comment by YolandaZheng** [comment]
Hi, 

Thanks for replying! I encountered some syntax error when first installing, but now after applying 2to3 to the package, the version related errors have disappeared and I seem to have successfully set it up. 

But here's new problem: when I run

```
>>> import praat_formants_python as pfp
>>> pfp.formants_at_interval('harry.wav', 0.5, 0.7)
```

Praat is successfully launched and a script window pops up: 
![screen shot 2016-04-27 at 10 04 20](https://cloud.githubusercontent.com/assets/18540024/14860835/736e0066-0c5f-11e6-9e82-fe4073ee41da.png)

However there's an error window too:
![screen shot 2016-04-27 at 10 05 08](https://cloud.githubusercontent.com/assets/18540024/14860856/8afe0e9c-0c5f-11e6-95d6-32fdd345d550.png)

What do you think is wrong?

Thanks!!

**Comment by YolandaZheng** [comment]
Hello,

Just now I put the full path of harry.wav when calling formants_at_interval (harry.wav is stored directly under the folder praat_formants_python-master), but the same error appeared. In addition to the "5500" error window, both times two other windows also appeared:
![screen shot 2016-04-27 at 10 13 43](https://cloud.githubusercontent.com/assets/18540024/14861375/d4cf5a2e-0c61-11e6-9a84-ce70c6093a2b.png)
![screen shot 2016-04-27 at 10 13 53](https://cloud.githubusercontent.com/assets/18540024/14861379/da2cd44c-0c61-11e6-9684-e2b83a9a198a.png)

After I closed Praat, this error popped up on my terminal:

```
>>> import praat_formants_python as pfp
>>> pfp.formants_at_interval('/Users/Yolanda/Downloads/praat_formants_python-master/harry.wav', 1.1, 2.1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Yolanda/Downloads/praat_formants_python-master/praat_formants_python/_formants.py", line 143, in formants_at_interval
    formants_array = file2formants(filename, **kwargs)
  File "/Users/Yolanda/Downloads/praat_formants_python-master/praat_formants_python/_formants.py", line 98, in file2formants
    _fmt_cache[key] = np.array([list(map(_float, x.rstrip().split('\t')[:4])) for x in res.split('\n')[1:-1]])
TypeError: 'str' does not support the buffer interface 
```

Hope you can help! Thanks ^_^

**Comment by thefreakingmind** [comment]
@YolandaZheng  Kindly put the pull request for the same. I fixed mine but it will save people from the error.

**Comment by b-schnell** [comment]
@thefreakingmind12 Would you be so kind to point out how you fixed the 5500 etc. errors?

Edit: Never mind, I fixed it for me, see pull request https://github.com/mwv/praat_formants_python/pull/3

**Comment by mwv** [comment]
Merged, thanks!
